console.log(Math.E)
console.log(Math.PI)
console.log(Math.round(Math.PI))
console.log(Math.max(400,500))
console.log(Math.min(400,500))
console.log(Math.pow(2,3))
console.log(Math.pow(3,5))
console.log(Math.sqrt(9))
console.log(Math.round(Math.random() * 50 + 1))